export const masterCatalog = [
  {
    shreni: "पाइप-फिटिंग",
    samaan: [
      { naam: "GI पाइप 0.5 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "7306" },
      { naam: "GI पाइप 0.75 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "7306" },
      { naam: "GI पाइप 1 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "7306" },
      { naam: "GI पाइप 1.5 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "7306" },
      { naam: "GI पाइप 2 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "7306" },
      { naam: "PVC पाइप 0.5 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC पाइप 0.75 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC पाइप 1 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC पाइप 1.5 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC पाइप 2 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC पाइप 3 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC पाइप 4 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "CPVC पाइप 0.5 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "CPVC पाइप 0.75 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "CPVC पाइप 1 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "GI एल्बो 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI एल्बो 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI एल्बो 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI टी 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI टी 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI टी 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI यूनियन 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI यूनियन 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI यूनियन 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI निप्पल 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI निप्पल 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI रिड्यूसर 1x0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "बॉल वाल्व 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "बॉल वाल्व 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "बॉल वाल्व 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "बॉल वाल्व 1.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "गेट वाल्व 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "गेट वाल्व 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "गेट वाल्व 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "चेक वाल्व 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "PVC एल्बो 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC एल्बो 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC एल्बो 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC टी 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC टी 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC टी 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC कपलिंग 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC कपलिंग 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC रिड्यूसर 1x0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "पाइप क्लैंप 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "पाइप क्लैंप 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "पाइप क्लैंप 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "फ्लेक्सिबल पाइप 0.5 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "फ्लेक्सिबल पाइप 0.75 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
    ],
  },
  {
    shreni: "सेनेटरी",
    samaan: [
      { naam: "वेस्टर्न कमोड (सफेद)", ikaai: "नग", gstDar: 18, hsnCode: "6910" },
      { naam: "इंडियन कमोड (सफेद)", ikaai: "नग", gstDar: 18, hsnCode: "6910" },
      { naam: "वाशबेसिन (सफेद)", ikaai: "नग", gstDar: 18, hsnCode: "6910" },
      { naam: "यूरिनल (सफेद)", ikaai: "नग", gstDar: 18, hsnCode: "6910" },
      { naam: "फ्लश टैंक", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "सीट कवर", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "पिलर कॉक", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "बेसिन मिक्सर", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "शॉवर मिक्सर", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "हैंड शॉवर", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "ओवरहेड शॉवर", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "वाल मिक्सर", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "पी-ट्रैप", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "एस-ट्रैप", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "फ्लोर ट्रैप 4 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "बोतल ट्रैप", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "एंगल वाल्व", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "स्टॉप कॉक", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "बाथटब", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "शॉवर ट्रे", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "टॉवल रॉड SS", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "साबुन दानी SS", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "टिशू होल्डर SS", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "नैपकिन रिंग SS", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "शीशा (बाथरूम) 18x24", ikaai: "नग", gstDar: 18, hsnCode: "7009" },
    ],
  },
  {
    shreni: "किचन",
    samaan: [
      { naam: "SS सिंक सिंगल बाउल 24x18", ikaai: "नग", gstDar: 18, hsnCode: "7324" },
      { naam: "SS सिंक डबल बाउल 45x20", ikaai: "नग", gstDar: 18, hsnCode: "7324" },
      { naam: "क्वार्ट्ज सिंक सिंगल", ikaai: "नग", gstDar: 18, hsnCode: "7324" },
      { naam: "किचन मिक्सर नल", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "किचन नल सिंगल होल", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "सिंक ड्रेनेज बास्केट", ikaai: "नग", gstDar: 18, hsnCode: "7324" },
      { naam: "सिंक कपलिंग", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "किचन हुक SS (5 नग)", ikaai: "सेट", gstDar: 18, hsnCode: "8302" },
      { naam: "किचन शेल्फ SS", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
    ],
  },
  {
    shreni: "टाइल्स-ग्राउट",
    samaan: [
      { naam: "फ्लोर टाइल 2x2 फीट", ikaai: "वर्ग फीट", gstDar: 18, hsnCode: "6907" },
      { naam: "वॉल टाइल 1x1.5 फीट", ikaai: "वर्ग फीट", gstDar: 18, hsnCode: "6907" },
      { naam: "विट्रिफाइड टाइल 2x2", ikaai: "वर्ग फीट", gstDar: 18, hsnCode: "6907" },
      { naam: "विट्रिफाइड टाइल 2x4", ikaai: "वर्ग फीट", gstDar: 18, hsnCode: "6907" },
      { naam: "मोजेक टाइल", ikaai: "वर्ग फीट", gstDar: 18, hsnCode: "6907" },
      { naam: "टाइल एडहेसिव 20kg", ikaai: "बैग", gstDar: 18, hsnCode: "3214" },
      { naam: "ग्राउट सफेद 1kg", ikaai: "पैकेट", gstDar: 18, hsnCode: "3214" },
      { naam: "ग्राउट रंगीन 1kg", ikaai: "पैकेट", gstDar: 18, hsnCode: "3214" },
      { naam: "टाइल स्पेसर", ikaai: "पैकेट", gstDar: 18, hsnCode: "3926" },
      { naam: "टाइल कटर", ikaai: "नग", gstDar: 18, hsnCode: "8467" },
      { naam: "टाइल नॉकर", ikaai: "नग", gstDar: 18, hsnCode: "8205" },
      { naam: "सीमेंट बेस प्राइमर 1L", ikaai: "लीटर", gstDar: 18, hsnCode: "3214" },
    ],
  },
  {
    shreni: "बिजली",
    samaan: [
      { naam: "तार 1.5 स्क्वायर (100 मीटर)", ikaai: "रोल", gstDar: 18, hsnCode: "8544" },
      { naam: "तार 2.5 स्क्वायर (100 मीटर)", ikaai: "रोल", gstDar: 18, hsnCode: "8544" },
      { naam: "तार 4 स्क्वायर (100 मीटर)", ikaai: "रोल", gstDar: 18, hsnCode: "8544" },
      { naam: "तार 6 स्क्वायर (100 मीटर)", ikaai: "रोल", gstDar: 18, hsnCode: "8544" },
      { naam: "तार 10 स्क्वायर (100 मीटर)", ikaai: "रोल", gstDar: 18, hsnCode: "8544" },
      { naam: "मॉड्यूलर स्विच", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "मॉड्यूलर सॉकेट", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "मॉड्यूलर फेस प्लेट 1M", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "मॉड्यूलर फेस प्लेट 2M", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "मॉड्यूलर फेस प्लेट 3M", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "MCB 6A", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "MCB 16A", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "MCB 32A", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "MCB 63A", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "DB बॉक्स 4 वे", ikaai: "नग", gstDar: 18, hsnCode: "8537" },
      { naam: "DB बॉक्स 8 वे", ikaai: "नग", gstDar: 18, hsnCode: "8537" },
      { naam: "DB बॉक्स 12 वे", ikaai: "नग", gstDar: 18, hsnCode: "8537" },
      { naam: "PVC कंड्यूट पाइप 20mm", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC कंड्यूट पाइप 25mm", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "जंक्शन बॉक्स", ikaai: "नग", gstDar: 18, hsnCode: "8537" },
      { naam: "LED बल्ब 9W", ikaai: "नग", gstDar: 12, hsnCode: "8539" },
      { naam: "LED बल्ब 15W", ikaai: "नग", gstDar: 12, hsnCode: "8539" },
      { naam: "LED बल्ब 20W", ikaai: "नग", gstDar: 12, hsnCode: "8539" },
      { naam: "LED ट्यूबलाइट 20W", ikaai: "नग", gstDar: 12, hsnCode: "8539" },
      { naam: "LED ट्यूबलाइट 40W", ikaai: "नग", gstDar: 12, hsnCode: "8539" },
      { naam: "पंखा (सीलिंग)", ikaai: "नग", gstDar: 18, hsnCode: "8414" },
      { naam: "पंखा (टेबल)", ikaai: "नग", gstDar: 18, hsnCode: "8414" },
      { naam: "पंखा (दीवार)", ikaai: "नग", gstDar: 18, hsnCode: "8414" },
      { naam: "एग्जॉस्ट पंखा 6 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8414" },
      { naam: "एग्जॉस्ट पंखा 9 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8414" },
      { naam: "बिजली टेप", ikaai: "रोल", gstDar: 18, hsnCode: "3919" },
      { naam: "बेकेलाइट बोर्ड 3 प्वाइंट", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "बेकेलाइट बोर्ड 6 प्वाइंट", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
    ],
  },
  {
    shreni: "रंग-पुट्टी",
    samaan: [
      { naam: "एशियन पेंट ट्रैक्टर 1 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "एशियन पेंट ट्रैक्टर 4 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "एशियन पेंट ट्रैक्टर 10 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "एशियन पेंट एपेक्स 1 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "एशियन पेंट एपेक्स 4 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "बर्जर वेदरकोट 1 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "बर्जर वेदरकोट 4 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "नेरोलैक एक्सेल 1 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "नेरोलैक एक्सेल 4 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "प्राइमर 1 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "प्राइमर 4 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "दीवार पुट्टी 5kg", ikaai: "बैग", gstDar: 18, hsnCode: "3214" },
      { naam: "दीवार पुट्टी 20kg", ikaai: "बैग", gstDar: 18, hsnCode: "3214" },
      { naam: "डिस्टेंपर 1kg", ikaai: "kg", gstDar: 18, hsnCode: "3209" },
      { naam: "डिस्टेंपर 5kg", ikaai: "kg", gstDar: 18, hsnCode: "3209" },
      { naam: "डिस्टेंपर 10kg", ikaai: "kg", gstDar: 18, hsnCode: "3209" },
      { naam: "पेंट ब्रश 2 इंच", ikaai: "नग", gstDar: 18, hsnCode: "9603" },
      { naam: "पेंट ब्रश 4 इंच", ikaai: "नग", gstDar: 18, hsnCode: "9603" },
      { naam: "रोलर ब्रश", ikaai: "नग", gstDar: 18, hsnCode: "9603" },
      { naam: "रोलर ट्रे", ikaai: "नग", gstDar: 18, hsnCode: "9603" },
      { naam: "मैस्टिक पेंट 4 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "तेल रंग (काला) 1 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "तेल रंग (लाल) 1 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "तेल रंग (हरा) 1 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "एनामेल पेंट सफेद 1 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "एनामेल पेंट सफेद 4 लीटर", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "थिनर 1 लीटर", ikaai: "लीटर", gstDar: 18, hsnCode: "3814" },
      { naam: "थिनर 5 लीटर", ikaai: "लीटर", gstDar: 18, hsnCode: "3814" },
    ],
  },
  {
    shreni: "औजार",
    samaan: [
      { naam: "हथौड़ा 500g", ikaai: "नग", gstDar: 18, hsnCode: "8205" },
      { naam: "हथौड़ा 1kg", ikaai: "नग", gstDar: 18, hsnCode: "8205" },
      { naam: "हथौड़ा 2kg", ikaai: "नग", gstDar: 18, hsnCode: "8205" },
      { naam: "पेचकस सेट", ikaai: "सेट", gstDar: 18, hsnCode: "8205" },
      { naam: "रेती सेट", ikaai: "सेट", gstDar: 18, hsnCode: "8203" },
      { naam: "पाना सेट", ikaai: "सेट", gstDar: 18, hsnCode: "8204" },
      { naam: "प्लास (नोज)", ikaai: "नग", gstDar: 18, hsnCode: "8203" },
      { naam: "मेजरिंग टेप 3 मीटर", ikaai: "नग", gstDar: 18, hsnCode: "9017" },
      { naam: "मेजरिंग टेप 5 मीटर", ikaai: "नग", gstDar: 18, hsnCode: "9017" },
      { naam: "ड्रिल बिट सेट", ikaai: "सेट", gstDar: 18, hsnCode: "8207" },
      { naam: "हैक्सॉ फ्रेम", ikaai: "नग", gstDar: 18, hsnCode: "8202" },
      { naam: "हैक्सॉ ब्लेड", ikaai: "पैकेट", gstDar: 18, hsnCode: "8202" },
      { naam: "साहुल (स्तर)", ikaai: "नग", gstDar: 18, hsnCode: "9017" },
      { naam: "पाइप रेंच 14 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8204" },
      { naam: "पाइप कटर", ikaai: "नग", gstDar: 18, hsnCode: "8203" },
      { naam: "छेनी सेट", ikaai: "सेट", gstDar: 18, hsnCode: "8205" },
      { naam: "कटर चाकू", ikaai: "नग", gstDar: 18, hsnCode: "8211" },
      { naam: "लोहा काटने की कैंची", ikaai: "नग", gstDar: 18, hsnCode: "8203" },
      { naam: "ग्राइंडर कटिंग डिस्क", ikaai: "नग", gstDar: 18, hsnCode: "6804" },
      { naam: "बरमा सेट", ikaai: "सेट", gstDar: 18, hsnCode: "8207" },
      { naam: "वायर स्ट्रिपर", ikaai: "नग", gstDar: 18, hsnCode: "8203" },
      { naam: "मल्टीमीटर", ikaai: "नग", gstDar: 18, hsnCode: "9030" },
    ],
  },
  {
    shreni: "दरवाजा-खिड़की",
    samaan: [
      { naam: "कब्जा SS 4 इंच", ikaai: "जोड़ी", gstDar: 18, hsnCode: "8302" },
      { naam: "कब्जा SS 5 इंच", ikaai: "जोड़ी", gstDar: 18, hsnCode: "8302" },
      { naam: "कब्जा SS 6 इंच", ikaai: "जोड़ी", gstDar: 18, hsnCode: "8302" },
      { naam: "मॉर्टिस ताला", ikaai: "नग", gstDar: 18, hsnCode: "8301" },
      { naam: "दरवाजा हैंडल SS", ikaai: "जोड़ी", gstDar: 18, hsnCode: "8302" },
      { naam: "सिटकनी 6 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "सिटकनी 10 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "कुंडी", ikaai: "नग", gstDar: 18, hsnCode: "8301" },
      { naam: "दरवाजा रोकनी", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "दरवाजा बंद करनी", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "खिड़की स्लाइडर", ikaai: "सेट", gstDar: 18, hsnCode: "8302" },
      { naam: "खिड़की हैंडल", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "हुक और आँख", ikaai: "जोड़ी", gstDar: 18, hsnCode: "8302" },
      { naam: "ताला 50mm", ikaai: "नग", gstDar: 18, hsnCode: "8301" },
      { naam: "ताला 65mm", ikaai: "नग", gstDar: 18, hsnCode: "8301" },
      { naam: "ताला 75mm", ikaai: "नग", gstDar: 18, hsnCode: "8301" },
      { naam: "ताला 100mm", ikaai: "नग", gstDar: 18, hsnCode: "8301" },
      { naam: "दरवाजा स्प्रिंग", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "दरवाजा आई होल", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
    ],
  },
  {
    shreni: "फास्टनर-स्क्रू",
    samaan: [
      { naam: "लकड़ी पेंच 1 इंच (100 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "लकड़ी पेंच 1.5 इंच (100 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "लकड़ी पेंच 2 इंच (100 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "लकड़ी पेंच 2.5 इंच (100 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "सेल्फ टैपिंग पेंच (100 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "नट-बोल्ट M6 (50 सेट)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "नट-बोल्ट M8 (50 सेट)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "नट-बोल्ट M10 (50 सेट)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "एंकर 6mm (100 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "एंकर 8mm (100 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "एंकर 10mm (100 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "दीवार खूंटी (100 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "3926" },
      { naam: "रिवेट (100 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "वॉशर M6 (100 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "कील 1 इंच (250g)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7317" },
      { naam: "कील 2 इंच (250g)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7317" },
      { naam: "कील 3 इंच (250g)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7317" },
      { naam: "कील 4 इंच (250g)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7317" },
      { naam: "J-हुक (10 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "8302" },
    ],
  },
  {
    shreni: "सीलेंट-केमिकल",
    samaan: [
      { naam: "सिलिकॉन सीलेंट (सफेद)", ikaai: "नग", gstDar: 18, hsnCode: "3214" },
      { naam: "सिलिकॉन सीलेंट (साफ)", ikaai: "नग", gstDar: 18, hsnCode: "3214" },
      { naam: "एम-सील 50g", ikaai: "नग", gstDar: 18, hsnCode: "3214" },
      { naam: "एम-सील 200g", ikaai: "नग", gstDar: 18, hsnCode: "3214" },
      { naam: "PVC सोल्वेंट 100ml", ikaai: "नग", gstDar: 18, hsnCode: "3506" },
      { naam: "PVC सोल्वेंट 500ml", ikaai: "नग", gstDar: 18, hsnCode: "3506" },
      { naam: "टेफलॉन टेप 12mm", ikaai: "रोल", gstDar: 18, hsnCode: "5906" },
      { naam: "टेफलॉन टेप 25mm", ikaai: "रोल", gstDar: 18, hsnCode: "5906" },
      { naam: "फेविकोल 1kg", ikaai: "kg", gstDar: 18, hsnCode: "3506" },
      { naam: "फेविकोल 5kg", ikaai: "kg", gstDar: 18, hsnCode: "3506" },
      { naam: "अराल्डाइट (जल्दी)", ikaai: "नग", gstDar: 18, hsnCode: "3506" },
      { naam: "तेल स्प्रे (WD)", ikaai: "नग", gstDar: 18, hsnCode: "3403" },
      { naam: "ग्रीस 500g", ikaai: "डिब्बा", gstDar: 18, hsnCode: "2710" },
      { naam: "वॉटरप्रूफ कंपाउंड 1kg", ikaai: "kg", gstDar: 18, hsnCode: "3214" },
      { naam: "वॉटरप्रूफ कंपाउंड 5kg", ikaai: "kg", gstDar: 18, hsnCode: "3214" },
    ],
  },
  {
    shreni: "वॉटर टैंक-पंप",
    samaan: [
      { naam: "पानी टंकी 500 लीटर", ikaai: "नग", gstDar: 18, hsnCode: "3925" },
      { naam: "पानी टंकी 1000 लीटर", ikaai: "नग", gstDar: 18, hsnCode: "3925" },
      { naam: "पानी टंकी 2000 लीटर", ikaai: "नग", gstDar: 18, hsnCode: "3925" },
      { naam: "ज़मीन के नीचे टंकी 1000 लीटर", ikaai: "नग", gstDar: 18, hsnCode: "3925" },
      { naam: "मोनोब्लॉक पंप 0.5 घोड़ा", ikaai: "नग", gstDar: 18, hsnCode: "8413" },
      { naam: "मोनोब्लॉक पंप 1 घोड़ा", ikaai: "नग", gstDar: 18, hsnCode: "8413" },
      { naam: "मोनोब्लॉक पंप 2 घोड़ा", ikaai: "नग", gstDar: 18, hsnCode: "8413" },
      { naam: "सबमर्सिबल पंप 0.5 घोड़ा", ikaai: "नग", gstDar: 18, hsnCode: "8413" },
      { naam: "सबमर्सिबल पंप 1 घोड़ा", ikaai: "नग", gstDar: 18, hsnCode: "8413" },
      { naam: "फ्लोट वाल्व 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "फ्लोट वाल्व 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "फ्लोट वाल्व 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
    ],
  },
  {
    shreni: "सीमेंट-बालू-गिट्टी",
    samaan: [
      { naam: "सीमेंट 50kg (बोरी)", ikaai: "बोरी", gstDar: 28, hsnCode: "2523" },
      { naam: "बालू (रेत) 1 घनमीटर", ikaai: "घनमीटर", gstDar: 5, hsnCode: "2505" },
      { naam: "गिट्टी (20mm) 1 घनमीटर", ikaai: "घनमीटर", gstDar: 5, hsnCode: "2517" },
      { naam: "गिट्टी (10mm) 1 घनमीटर", ikaai: "घनमीटर", gstDar: 5, hsnCode: "2517" },
      { naam: "सफेद सीमेंट 5kg", ikaai: "बैग", gstDar: 28, hsnCode: "2523" },
      { naam: "सफेद सीमेंट 1kg", ikaai: "kg", gstDar: 28, hsnCode: "2523" },
      { naam: "ईंट (लाल)", ikaai: "नग", gstDar: 5, hsnCode: "6901" },
      { naam: "फ्लाई ऐश ब्लॉक 6 इंच", ikaai: "नग", gstDar: 12, hsnCode: "6810" },
      { naam: "फ्लाई ऐश ब्लॉक 9 इंच", ikaai: "नग", gstDar: 12, hsnCode: "6810" },
      { naam: "कंक्रीट ब्लॉक 6 इंच", ikaai: "नग", gstDar: 12, hsnCode: "6810" },
    ],
  },
  {
    shreni: "छत-चादर",
    samaan: [
      { naam: "टीन चादर 8 फीट", ikaai: "नग", gstDar: 18, hsnCode: "7210" },
      { naam: "टीन चादर 10 फीट", ikaai: "नग", gstDar: 18, hsnCode: "7210" },
      { naam: "टीन चादर 12 फीट", ikaai: "नग", gstDar: 18, hsnCode: "7210" },
      { naam: "रंगीन चादर 8 फीट", ikaai: "नग", gstDar: 18, hsnCode: "7210" },
      { naam: "रंगीन चादर 10 फीट", ikaai: "नग", gstDar: 18, hsnCode: "7210" },
      { naam: "पॉलीकार्बोनेट शीट 8 फीट", ikaai: "नग", gstDar: 18, hsnCode: "3920" },
      { naam: "पॉलीकार्बोनेट शीट 10 फीट", ikaai: "नग", gstDar: 18, hsnCode: "3920" },
      { naam: "एस्बेस्टस शीट 8 फीट", ikaai: "नग", gstDar: 18, hsnCode: "6811" },
      { naam: "एस्बेस्टस शीट 10 फीट", ikaai: "नग", gstDar: 18, hsnCode: "6811" },
      { naam: "रिज कैप", ikaai: "नग", gstDar: 18, hsnCode: "7210" },
      { naam: "चादर पेंच (100 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "छत वॉटरप्रूफ शीट 4x8 फीट", ikaai: "नग", gstDar: 18, hsnCode: "3920" },
    ],
  },
  {
    shreni: "लोहा-सरिया",
    samaan: [
      { naam: "सरिया 8mm (1 छड़)", ikaai: "छड़", gstDar: 18, hsnCode: "7213" },
      { naam: "सरिया 10mm (1 छड़)", ikaai: "छड़", gstDar: 18, hsnCode: "7213" },
      { naam: "सरिया 12mm (1 छड़)", ikaai: "छड़", gstDar: 18, hsnCode: "7213" },
      { naam: "सरिया 16mm (1 छड़)", ikaai: "छड़", gstDar: 18, hsnCode: "7213" },
      { naam: "एंगल 25x25x3mm (6 मीटर)", ikaai: "नग", gstDar: 18, hsnCode: "7216" },
      { naam: "एंगल 40x40x4mm (6 मीटर)", ikaai: "नग", gstDar: 18, hsnCode: "7216" },
      { naam: "चैनल (6 मीटर)", ikaai: "नग", gstDar: 18, hsnCode: "7216" },
      { naam: "फ्लैट बार 25x6mm (6 मीटर)", ikaai: "नग", gstDar: 18, hsnCode: "7228" },
      { naam: "GI तार 18 गेज (1kg)", ikaai: "kg", gstDar: 18, hsnCode: "7217" },
      { naam: "GI तार 20 गेज (1kg)", ikaai: "kg", gstDar: 18, hsnCode: "7217" },
      { naam: "बाइंडिंग तार 1kg", ikaai: "kg", gstDar: 18, hsnCode: "7217" },
      { naam: "MS प्लेट 3mm (1 वर्ग फीट)", ikaai: "वर्ग फीट", gstDar: 18, hsnCode: "7208" },
    ],
  },
  {
    shreni: "प्लास्टिक-बाल्टी-ड्रम",
    samaan: [
      { naam: "बाल्टी 10 लीटर", ikaai: "नग", gstDar: 18, hsnCode: "3924" },
      { naam: "बाल्टी 15 लीटर", ikaai: "नग", gstDar: 18, hsnCode: "3924" },
      { naam: "बाल्टी 20 लीटर", ikaai: "नग", gstDar: 18, hsnCode: "3924" },
      { naam: "ड्रम 50 लीटर", ikaai: "नग", gstDar: 18, hsnCode: "3923" },
      { naam: "ड्रम 100 लीटर", ikaai: "नग", gstDar: 18, hsnCode: "3923" },
      { naam: "ड्रम 200 लीटर", ikaai: "नग", gstDar: 18, hsnCode: "3923" },
      { naam: "मग 1 लीटर", ikaai: "नग", gstDar: 18, hsnCode: "3924" },
      { naam: "तसला (बड़ा)", ikaai: "नग", gstDar: 18, hsnCode: "3924" },
      { naam: "तसला (छोटा)", ikaai: "नग", gstDar: 18, hsnCode: "3924" },
      { naam: "पानी कैन 20 लीटर", ikaai: "नग", gstDar: 18, hsnCode: "3923" },
      { naam: "फुव्वारा (8 छेद)", ikaai: "नग", gstDar: 18, hsnCode: "8424" },
      { naam: "पाइप नली 1 इंच (10 मीटर)", ikaai: "रोल", gstDar: 18, hsnCode: "3917" },
      { naam: "पाइप नली 0.75 इंच (10 मीटर)", ikaai: "रोल", gstDar: 18, hsnCode: "3917" },
    ],
  },
  {
    shreni: "रस्सी-जाल-तार",
    samaan: [
      { naam: "नायलॉन रस्सी 6mm (50 मीटर)", ikaai: "रोल", gstDar: 12, hsnCode: "5607" },
      { naam: "नायलॉन रस्सी 10mm (50 मीटर)", ikaai: "रोल", gstDar: 12, hsnCode: "5607" },
      { naam: "PP रस्सी 6mm (50 मीटर)", ikaai: "रोल", gstDar: 12, hsnCode: "5607" },
      { naam: "लोहे की जाली (चेन लिंक) 1 मीटर", ikaai: "मीटर", gstDar: 18, hsnCode: "7314" },
      { naam: "सुतली (जूट) 500g", ikaai: "गट्ठर", gstDar: 5, hsnCode: "5607" },
      { naam: "बारबड तार (कंटीली) 50 मीटर", ikaai: "रोल", gstDar: 18, hsnCode: "7313" },
      { naam: "चिकन जाली 1 मीटर चौड़ी", ikaai: "मीटर", gstDar: 18, hsnCode: "7314" },
      { naam: "मच्छर जाली 1 मीटर चौड़ी", ikaai: "मीटर", gstDar: 12, hsnCode: "5608" },
      { naam: "GI जाली 1x1 इंच 1 मीटर चौड़ी", ikaai: "मीटर", gstDar: 18, hsnCode: "7314" },
      { naam: "जंजीर 3mm (1 मीटर)", ikaai: "मीटर", gstDar: 18, hsnCode: "7315" },
    ],
  },
  {
    shreni: "सुरक्षा-हेलमेट",
    samaan: [
      { naam: "हेलमेट (पीला)", ikaai: "नग", gstDar: 18, hsnCode: "6506" },
      { naam: "हेलमेट (सफेद)", ikaai: "नग", gstDar: 18, hsnCode: "6506" },
      { naam: "दस्ताने (चमड़ा)", ikaai: "जोड़ी", gstDar: 12, hsnCode: "6216" },
      { naam: "दस्ताने (रबर)", ikaai: "जोड़ी", gstDar: 12, hsnCode: "6216" },
      { naam: "आँख बचाव चश्मा", ikaai: "नग", gstDar: 18, hsnCode: "9004" },
      { naam: "कमर बेल्ट (सेफ्टी)", ikaai: "नग", gstDar: 18, hsnCode: "6307" },
      { naam: "जूते (सेफ्टी)", ikaai: "जोड़ी", gstDar: 18, hsnCode: "6403" },
      { naam: "मास्क (धूल)", ikaai: "नग", gstDar: 12, hsnCode: "6307" },
    ],
  },
  {
    shreni: "घर की साज-सज्जा",
    samaan: [
      { naam: "दीवार हुक (5 नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "8302" },
      { naam: "शेल्फ ब्रैकेट (जोड़ी)", ikaai: "जोड़ी", gstDar: 18, hsnCode: "8302" },
      { naam: "रॉड होल्डर", ikaai: "जोड़ी", gstDar: 18, hsnCode: "8302" },
      { naam: "पर्दा छड़ 5 फीट", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "पर्दा छड़ 7 फीट", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "तस्वीर फ्रेम हुक", ikaai: "पैकेट", gstDar: 18, hsnCode: "8302" },
      { naam: "कपड़े सुखाने की छड़", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "स्टील रैक शेल्फ", ikaai: "नग", gstDar: 18, hsnCode: "9403" },
      { naam: "नल (पानी) सिंपल", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "नल (पानी) घुमाव वाला", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
    ],
  },
]