export const masterCatalog = [
  {
    shreni: "पाइप-फिटिंग",
    samaan: [
      { naam: "GI पाइप 0.5 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "7306" },
      { naam: "GI पाइप 0.75 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "7306" },
      { naam: "GI पाइप 1 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "7306" },
      { naam: "GI पाइप 1.5 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "7306" },
      { naam: "GI पाइप 2 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "7306" },
      { naam: "PVC पाइप 0.5 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC पाइप 0.75 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC पाइप 1 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC पाइप 1.5 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC पाइप 2 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "CPVC पाइप 0.5 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "CPVC पाइप 0.75 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "CPVC पाइप 1 इंच", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "GI एल्बो 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI एल्बो 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI एल्बो 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI टी 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI टी 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI टी 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI यूनियन 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI यूनियन 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI यूनियन 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI निप्पल 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI निप्पल 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "GI रिड्यूसर 1x0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "बॉल वाल्व 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "बॉल वाल्व 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "बॉल वाल्व 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "गेट वाल्व 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "गेट वाल्व 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "चेक वाल्व 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "PVC एल्बो 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC एल्बो 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC टी 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
      { naam: "PVC कपलिंग 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
    ],
  },
  {
    shreni: "सेनेटरी",
    samaan: [
      { naam: "वेस्टर्न कमोड (सफेद)", ikaai: "नग", gstDar: 18, hsnCode: "6910" },
      { naam: "इंडियन कमोड (सफेद)", ikaai: "नग", gstDar: 18, hsnCode: "6910" },
      { naam: "वाशबेसिन (सफेद)", ikaai: "नग", gstDar: 18, hsnCode: "6910" },
      { naam: "यूरिनल (सफेद)", ikaai: "नग", gstDar: 18, hsnCode: "6910" },
      { naam: "फ्लश टैंक", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "सीट कवर", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "पिलर कॉक", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "बेसिन मिक्सर", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "शॉवर मिक्सर", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "हैंड शॉवर", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "ओवरहेड शॉवर", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "वाल मिक्सर", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "P-ट्रैप", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "S-ट्रैप", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "फ्लोर ट्रैप 4 इंच", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "बोतल ट्रैप", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "एंगल वाल्व", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "स्टॉप कॉक", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "बाथटब", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
      { naam: "शॉवर ट्रे", ikaai: "नग", gstDar: 18, hsnCode: "3922" },
    ],
  },
  {
    shreni: "किचन",
    samaan: [
      { naam: "SS सिंक सिंगल बाउल 24x18", ikaai: "नग", gstDar: 18, hsnCode: "7324" },
      { naam: "SS सिंक डबल बाउल 45x20", ikaai: "नग", gstDar: 18, hsnCode: "7324" },
      { naam: "क्वार्ट्ज सिंक सिंगल", ikaai: "नग", gstDar: 18, hsnCode: "7324" },
      { naam: "किचन मिक्सर नल", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "किचन नल सिंगल होल", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "सिंक ड्रेनेज बास्केट", ikaai: "नग", gstDar: 18, hsnCode: "7324" },
      { naam: "सिंक कपलिंग", ikaai: "नग", gstDar: 18, hsnCode: "3917" },
    ],
  },
  {
    shreni: "टाइल्स-ग्राउट",
    samaan: [
      { naam: "फ्लोर टाइल 2x2 फीट", ikaai: "वर्ग फीट", gstDar: 18, hsnCode: "6907" },
      { naam: "वॉल टाइल 1x1.5 फीट", ikaai: "वर्ग फीट", gstDar: 18, hsnCode: "6907" },
      { naam: "विट्रिफाइड टाइल 2x2", ikaai: "वर्ग फीट", gstDar: 18, hsnCode: "6907" },
      { naam: "मोजेक टाइल", ikaai: "वर्ग फीट", gstDar: 18, hsnCode: "6907" },
      { naam: "टाइल एडहेसिव 20kg", ikaai: "बैग", gstDar: 18, hsnCode: "3214" },
      { naam: "ग्राउट सफेद 1kg", ikaai: "पैकेट", gstDar: 18, hsnCode: "3214" },
      { naam: "ग्राउट रंगीन 1kg", ikaai: "पैकेट", gstDar: 18, hsnCode: "3214" },
      { naam: "टाइल स्पेसर", ikaai: "पैकेट", gstDar: 18, hsnCode: "3926" },
      { naam: "टाइल कटर", ikaai: "नग", gstDar: 18, hsnCode: "8467" },
    ],
  },
  {
    shreni: "बिजली",
    samaan: [
      { naam: "1.5 Sq.mm तार (100m)", ikaai: "रोल", gstDar: 18, hsnCode: "8544" },
      { naam: "2.5 Sq.mm तार (100m)", ikaai: "रोल", gstDar: 18, hsnCode: "8544" },
      { naam: "4 Sq.mm तार (100m)", ikaai: "रोल", gstDar: 18, hsnCode: "8544" },
      { naam: "6 Sq.mm तार (100m)", ikaai: "रोल", gstDar: 18, hsnCode: "8544" },
      { naam: "मॉड्यूलर स्विच", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "मॉड्यूलर सॉकेट", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "MCB 6A", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "MCB 16A", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "MCB 32A", ikaai: "नग", gstDar: 18, hsnCode: "8536" },
      { naam: "DB बॉक्स 4 वे", ikaai: "नग", gstDar: 18, hsnCode: "8537" },
      { naam: "DB बॉक्स 8 वे", ikaai: "नग", gstDar: 18, hsnCode: "8537" },
      { naam: "PVC कंड्यूट पाइप 20mm", ikaai: "मीटर", gstDar: 18, hsnCode: "3917" },
      { naam: "जंक्शन बॉक्स", ikaai: "नग", gstDar: 18, hsnCode: "8537" },
      { naam: "LED बल्ब 9W", ikaai: "नग", gstDar: 12, hsnCode: "8539" },
      { naam: "LED बल्ब 15W", ikaai: "नग", gstDar: 12, hsnCode: "8539" },
      { naam: "LED ट्यूबलाइट 20W", ikaai: "नग", gstDar: 12, hsnCode: "8539" },
      { naam: "पंखा (सीलिंग)", ikaai: "नग", gstDar: 18, hsnCode: "8414" },
    ],
  },
  {
    shreni: "रंग-पुट्टी",
    samaan: [
      { naam: "Asian Paint Tractor Emulsion 1L", ikaai: "लीटर", gstDar: 18, hsnCode: "3209" },
      { naam: "Asian Paint Tractor Emulsion 4L", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "Asian Paint Tractor Emulsion 10L", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "Asian Paint Apex 1L", ikaai: "लीटर", gstDar: 18, hsnCode: "3209" },
      { naam: "Asian Paint Apex 4L", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "Berger WeatherCoat 1L", ikaai: "लीटर", gstDar: 18, hsnCode: "3209" },
      { naam: "Berger WeatherCoat 4L", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "Nerolac Excel 1L", ikaai: "लीटर", gstDar: 18, hsnCode: "3209" },
      { naam: "Nerolac Excel 4L", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "Primer 1L", ikaai: "लीटर", gstDar: 18, hsnCode: "3209" },
      { naam: "Primer 4L", ikaai: "डिब्बा", gstDar: 18, hsnCode: "3209" },
      { naam: "Wall Putty 5kg", ikaai: "बैग", gstDar: 18, hsnCode: "3214" },
      { naam: "Wall Putty 20kg", ikaai: "बैग", gstDar: 18, hsnCode: "3214" },
      { naam: "Distemper 1kg", ikaai: "kg", gstDar: 18, hsnCode: "3209" },
      { naam: "Distemper 5kg", ikaai: "kg", gstDar: 18, hsnCode: "3209" },
      { naam: "पेंट ब्रश 2 इंच", ikaai: "नग", gstDar: 18, hsnCode: "9603" },
      { naam: "पेंट ब्रश 4 इंच", ikaai: "नग", gstDar: 18, hsnCode: "9603" },
      { naam: "रोलर ब्रश", ikaai: "नग", gstDar: 18, hsnCode: "9603" },
    ],
  },
  {
    shreni: "औजार",
    samaan: [
      { naam: "हथौड़ा 500g", ikaai: "नग", gstDar: 18, hsnCode: "8205" },
      { naam: "हथौड़ा 1kg", ikaai: "नग", gstDar: 18, hsnCode: "8205" },
      { naam: "पेचकस सेट", ikaai: "सेट", gstDar: 18, hsnCode: "8205" },
      { naam: "रेती सेट", ikaai: "सेट", gstDar: 18, hsnCode: "8203" },
      { naam: "पाना सेट", ikaai: "सेट", gstDar: 18, hsnCode: "8204" },
      { naam: "प्लास (नोज)", ikaai: "नग", gstDar: 18, hsnCode: "8203" },
      { naam: "मेजरिंग टेप 3m", ikaai: "नग", gstDar: 18, hsnCode: "9017" },
      { naam: "मेजरिंग टेप 5m", ikaai: "नग", gstDar: 18, hsnCode: "9017" },
      { naam: "ड्रिल बिट सेट", ikaai: "सेट", gstDar: 18, hsnCode: "8207" },
      { naam: "हैक्सॉ फ्रेम", ikaai: "नग", gstDar: 18, hsnCode: "8202" },
      { naam: "हैक्सॉ ब्लेड", ikaai: "पैकेट", gstDar: 18, hsnCode: "8202" },
      { naam: "स्तर (Spirit Level)", ikaai: "नग", gstDar: 18, hsnCode: "9017" },
      { naam: "पाइप रेंच 14 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8204" },
      { naam: "पाइप कटर", ikaai: "नग", gstDar: 18, hsnCode: "8203" },
      { naam: "चिजल सेट", ikaai: "सेट", gstDar: 18, hsnCode: "8205" },
    ],
  },
  {
    shreni: "दरवाजा-खिड़की",
    samaan: [
      { naam: "SS हिंज 4 इंच", ikaai: "जोड़ी", gstDar: 18, hsnCode: "8302" },
      { naam: "SS हिंज 5 इंच", ikaai: "जोड़ी", gstDar: 18, hsnCode: "8302" },
      { naam: "मॉर्टिस लॉक", ikaai: "नग", gstDar: 18, hsnCode: "8301" },
      { naam: "डोर हैंडल SS", ikaai: "जोड़ी", gstDar: 18, hsnCode: "8302" },
      { naam: "टॉवर बोल्ट 6 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "टॉवर बोल्ट 10 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "कुंडी (लैच)", ikaai: "नग", gstDar: 18, hsnCode: "8301" },
      { naam: "डोर स्टॉपर", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "डोर क्लोजर", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "विंडो स्लाइडर", ikaai: "सेट", gstDar: 18, hsnCode: "8302" },
      { naam: "विंडो हैंडल", ikaai: "नग", gstDar: 18, hsnCode: "8302" },
      { naam: "हुक एंड आई", ikaai: "जोड़ी", gstDar: 18, hsnCode: "8302" },
      { naam: "पैड लॉक 50mm", ikaai: "नग", gstDar: 18, hsnCode: "8301" },
      { naam: "पैड लॉक 65mm", ikaai: "नग", gstDar: 18, hsnCode: "8301" },
    ],
  },
  {
    shreni: "फास्टनर-स्क्रू",
    samaan: [
      { naam: "वुड स्क्रू 1 इंच (100नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "वुड स्क्रू 1.5 इंच (100नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "वुड स्क्रू 2 इंच (100नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "सेल्फ टैपिंग स्क्रू (100नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "नट-बोल्ट M6 (50 सेट)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "नट-बोल्ट M8 (50 सेट)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "एंकर फास्टनर 6mm (100नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "एंकर फास्टनर 8mm (100नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "वॉल प्लग (100नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "3926" },
      { naam: "रिवेट (100नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
      { naam: "वॉशर M6 (100नग)", ikaai: "पैकेट", gstDar: 18, hsnCode: "7318" },
    ],
  },
  {
    shreni: "सीलेंट-केमिकल",
    samaan: [
      { naam: "सिलिकॉन सीलेंट (सफेद)", ikaai: "नग", gstDar: 18, hsnCode: "3214" },
      { naam: "सिलिकॉन सीलेंट (ट्रांसपेरेंट)", ikaai: "नग", gstDar: 18, hsnCode: "3214" },
      { naam: "M-सील (50g)", ikaai: "नग", gstDar: 18, hsnCode: "3214" },
      { naam: "M-सील (200g)", ikaai: "नग", gstDar: 18, hsnCode: "3214" },
      { naam: "PVC सोल्वेंट 100ml", ikaai: "नग", gstDar: 18, hsnCode: "3506" },
      { naam: "PVC सोल्वेंट 500ml", ikaai: "नग", gstDar: 18, hsnCode: "3506" },
      { naam: "टेफलॉन टेप (12mm)", ikaai: "रोल", gstDar: 18, hsnCode: "5906" },
      { naam: "टेफलॉन टेप (25mm)", ikaai: "रोल", gstDar: 18, hsnCode: "5906" },
      { naam: "फेविकोल SH 1kg", ikaai: "kg", gstDar: 18, hsnCode: "3506" },
      { naam: "फेविकोल SH 5kg", ikaai: "kg", gstDar: 18, hsnCode: "3506" },
      { naam: "Araldite (fast)", ikaai: "नग", gstDar: 18, hsnCode: "3506" },
      { naam: "WD-40 स्प्रे", ikaai: "नग", gstDar: 18, hsnCode: "3403" },
    ],
  },
  {
    shreni: "वॉटर टैंक-पंप",
    samaan: [
      { naam: "Sintex टैंक 500L", ikaai: "नग", gstDar: 18, hsnCode: "3925" },
      { naam: "Sintex टैंक 1000L", ikaai: "नग", gstDar: 18, hsnCode: "3925" },
      { naam: "Sintex टैंक 2000L", ikaai: "नग", gstDar: 18, hsnCode: "3925" },
      { naam: "अंडरग्राउंड टैंक 1000L", ikaai: "नग", gstDar: 18, hsnCode: "3925" },
      { naam: "मोनोब्लॉक पंप 0.5HP", ikaai: "नग", gstDar: 18, hsnCode: "8413" },
      { naam: "मोनोब्लॉक पंप 1HP", ikaai: "नग", gstDar: 18, hsnCode: "8413" },
      { naam: "सबमर्सिबल पंप 0.5HP", ikaai: "नग", gstDar: 18, hsnCode: "8413" },
      { naam: "पाइप क्लैंप 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "पाइप क्लैंप 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "पाइप क्लैंप 1 इंच", ikaai: "नग", gstDar: 18, hsnCode: "7307" },
      { naam: "फ्लोट वाल्व 0.5 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
      { naam: "फ्लोट वाल्व 0.75 इंच", ikaai: "नग", gstDar: 18, hsnCode: "8481" },
    ],
  },
]